#include "main.h"

void TIM4_Init(void)
{
	//This timer is configured to get each tick 1 us, this timer is used to implement a counter that function to send CAN messages each 500 ms
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN; //TIM4 clock enabled
	TIM4->PSC = 53; //ARR and PSC are configured to have a overflow each 1 ms, that means we have 1 us for each tick
	TIM4->ARR = 1000 - 1;
	TIM4->CR1 &= ~TIM_CR1_UDIS; // UEV enabled. The update event is generated by Counter overflow/underflow

	TIM4->DIER |= TIM_DIER_UIE; // Update interrupt enable
	NVIC_EnableIRQ(TIM4_IRQn);
	NVIC_SetPriority(TIM4_IRQn, 0);

	TIM4->CR1 |= TIM_CR1_CEN; // Counter enabled
}



